### ISSUE TITLE
How were bindings generated?

### ISSUE THREAD

**Issue by duane** [RustAudio/coreaudio-sys#3]
I'd like to add support for other parts of the audio toolbox; I'm not entirely sure how the bindings were generated. Is this documented somewhere?

Best,
Duane

**Comment by mitchmindtree** [comment]
Hi @duane :) Bindings were generated using the [`rust-bindgen` crate](https://github.com/servo/rust-bindgen). I don't remember the exact command as it was quite a while ago, however I remember being able to work it out using the program's `--help`. Would love to see support for stuff, good luck with it!

**Comment by Mousterian** [comment]
Hi @duane, I was working on something similar a while back, I ended up forking coreaudio-sys, and never got round to doing a pull request, sorry @mitchmindtree - I was able to regenerate bindings and add another framework, I remember it was a bit fiddly so I noted instructions here: https://github.com/Mousterian/coreaudio-sys/tree/playfile
That said it was a while ago, rust-bindgen may have moved on since then, so those instructions may not work now - rust-bindgen seemed to be going through a lot of breaking changes around that time.
